### ISSUE TITLE
大佬，自动签到失效了 是不是签到机制改了啊

### ISSUE THREAD

**Issue by YasuoQAQ** [mole828/2dfan-checkin#1]

**Comment by mole828** [comment]
2dfan添加了人机验证，不知道怎么办了

**Comment by YasuoQAQ** [comment]
> 2dfan添加了人机验证，不知道怎么办了

说是app端登录了会自动签到 是不是可以从这方面下手

**Comment by mole828** [comment]
最近不考虑了，得过段日子了。

**Comment by YasuoQAQ** [comment]
好的 我先订阅了 开启自动提醒

**Comment by twtan** [comment]
> 最近不考虑了，得过段日子了。

抓了一下手机版网页发现里面也有个authenticity_token 字段...只能回头抓一下看看app
的包

**Comment by mole828** [comment]
那个app，我没办法打开下载链接，有什么其他渠道嘛？

**Comment by twtan** [comment]
> 那个app，我没办法打开下载链接，有什么其他渠道嘛？
下载途径是这个
https://github.com/2dfan/galge_app

PS：你可以试一下手机版浏览器，手机版浏览器不需要验证，我抓包看了一下多了一个
https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=xxx&co=xxx&hl=zh-CN&v=xxx&size=invisible&cb=xxx
的封包可以获取验证token，直接分析一下这个参数应该能直接使用这个token来签到

**Comment by Joackk** [comment]
> > 那个app，我没办法打开下载链接，有什么其他渠道嘛？
> > 下载途径是这个
> > https://github.com/2dfan/galge_app
> 
> PS：你可以试一下手机版浏览器，手机版浏览器不需要验证，我抓包看了一下多了一个 https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=xxx&co=xxx&hl=zh-CN&v=xxx&size=invisible&cb=xxx 的封包可以获取验证token，直接分析一下这个参数应该能直接使用这个token来签到

那个人机验证有token就不验证了吗？

**Comment by twtan** [comment]
> > > 那个app，我没办法打开下载链接，有什么其他渠道嘛？
> > > 下载途径是这个
> > > https://github.com/2dfan/galge_app
> > 
> > 
> > PS：你可以试一下手机版浏览器，手机版浏览器不需要验证，我抓包看了一下多了一个 https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=xxx&co=xxx&hl=zh-CN&v=xxx&size=invisible&cb=xxx 的封包可以获取验证token，直接分析一下这个参数应该能直接使用这个token来签到
> 
> 那个人机验证有token就不验证了吗？

我测试的时候没弹出人机验证窗口，你自己试下看看会不会弹出，我是桌面edge用F12 模拟手机浏览器

**Comment by Joackk** [comment]
@twtan 我直接在pc浏览器签到没有弹人机验证，但是我用burp抓了签到的包发过去就提示要验证，很奇怪

**Comment by twtan** [comment]
> @twtan 我直接在pc浏览器签到没有弹人机验证，但是我用burp抓了签到的包发过去就提示要验证，很奇怪

我猜是需要更新body 里面的  g-recaptcha-response-data ，https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=xxx&co=xxx&hl=zh-CN&v=xxx&size=invisible&cb=xxx 这段取得的就是 g-recaptcha-response-data

**Comment by mole828** [comment]
fix at 86165b1e595dfa994f88ea0800fbb635aea02120

**Comment by Joackk** [comment]
> fix at [86165b1](https://github.com/mole828/2dfan-checkin/commit/86165b1e595dfa994f88ea0800fbb635aea02120)

大佬你这个脚本时只需要改api.py里的cookie和x-csrf就行了吗？

**Comment by Joackk** [comment]
> > @twtan 我直接在pc浏览器签到没有弹人机验证，但是我用burp抓了签到的包发过去就提示要验证，很奇怪
> 
> 我猜是需要更新body 里面的 g-recaptcha-response-data ，https://www.recaptcha.net/recaptcha/api2/anchor?ar=1&k=xxx&co=xxx&hl=zh-CN&v=xxx&size=invisible&cb=xxx 这段取得的就是 g-recaptcha-response-data

这个就很奇怪，我今天又签到直接就没验证，但是重新发包又要验证。

**Comment by mole828** [comment]
@Joackk 你需要了解一下Google recaptcha。
recaptcha 会分析页面中的人物行为来验证是否为机器人，例如鼠标移动之类的操作方式
你需要在最新的分支中修改 User 构造时候的 captcha_interface
我感觉用打码平台越过人机验证并不是光彩的事情，并没有写在readme里面

**Comment by Joackk** [comment]
> @Joackk 你需要了解一下Google recaptcha。 recaptcha 会分析页面中的人物行为来验证是否为机器人，例如鼠标移动之类的操作方式 你需要在最新的分支中修改 User 构造时候的 captcha_interface 我感觉用打码平台越过人机验证并不是光彩的事情，并没有写在readme里面

soga
